[package]
name = "rssh"
version = "0.1.0"
authors = ["Lars Petersen <info@lars-petersen.net>"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.2"
bytes = "0.4.12"
futures-util-preview = "0.3.0-alpha.18"
