[package]
name = "rssh"
version = "0.1.0"
authors = ["Lars Petersen <info@lars-petersen.net>"]
edition = "2018"

[dependencies]
async-std = "0.99.4"
futures-preview = "0.3.0-alpha.18"
futures-util-preview = "0.3.0-alpha.18"
num = "0.2.0"
x25519-dalek = "0.5.2"
rand_core = "0.4.2"
rand_os = "0.1.1"
sha2 = "0.8.0"
