cargo-features = ["strip"]

[package]
name = "rssh"
version = "0.1.0"
authors = ["Lars Petersen <info@lars-petersen.net>"]
edition = "2018"

[dependencies]
async-std = { version = "1.7.0", features = ["attributes", "unstable"] }
base64 = "0.13.0"
chacha20 = { version = "0.6.0", features = ["legacy"] }
ed25519-dalek = "1.0.1"
env_logger = { version = "0.8.2", default-features = false }
futures-timer = "3.0.2"
generic-array = "0.14.4"
hmac = "0.10.1"
libc = "0.2.80"
log = "0.4.11"
poly1305 = "0.6.1"
rand = "0.7.3"
sha-1 = "0.9.2"
sha2 = "0.9.2"
x25519-dalek = "1.1.0"
zeroize = "1.1.1"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
opt-level = "z"
strip = "symbols"

[[example]]
name = "rssh-proxy"

[[example]]
name = "rssh-server"
