[package]
name = "rssh"
version = "0.1.0"
authors = ["Lars Petersen <info@lars-petersen.net>"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.2"
bytes = "0.4.12"
futures-util-preview = "0.3.0-alpha.18"
num = "0.2.0"
quickcheck = "0.9.0"
rand = "0.7.0"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.8"